### ISSUE TITLE
Parmed cannot read the Amber file generated by interchange: FLAG RESIDUE_LABEL has 0 elements; expected 1

### ISSUE THREAD

**Issue by bieniekmateusz** [openforcefield/openff-interchange#666]
I use a smirnoff and generate .prm7 and .rst7 files. These appear fine in VMD. But Parmed (3.4.4 and 4.1.0) throws an error:
"parmed.exceptions.AmberError: FLAG RESIDUE_LABEL has 0 elements; expected 1"

[minimal_gh_example.zip](https://github.com/openforcefield/openff-interchange/files/11275492/minimal_gh_example.zip)

**Output**
```
Traceback (most recent call last):
  File "ig/pmd.py", line 4, in <module>
    pmd.amber.AmberParm('lig_CHEMBL3265016-1.prm7')
  File "path/mambaforge/envs/pmd/lib/python3.11/site-packages/parmed/amber/_amberparm.py", line 155, in __init__
    self.initialize_topology(xyz, box)
  File "path/mambaforge/envs/pmd/lib/python3.11/site-packages/parmed/amber/_amberparm.py", line 185, in initialize_topology
    self.load_structure()
  File "path/mambaforge/envs/pmd/lib/python3.11/site-packages/parmed/amber/_amberparm.py", line 478, in load_structure
    self._check_section_lengths()
  File "path/mambaforge/envs/pmd/lib/python3.11/site-packages/parmed/amber/_amberparm.py", line 1277, in _check_section_lengths
    check_length('RESIDUE_LABEL', nres)
  File "path/mambaforge/envs/pmd/lib/python3.11/site-packages/parmed/amber/_amberparm.py", line 1257, in check_length
    raise AmberError(f'FLAG {key} has {len(self.parm_data[key])} elements; expected {length}')
parmed.exceptions.AmberError: FLAG RESIDUE_LABEL has 0 elements; expected 1

```

**Software versions**
- Arch Linux
- How did you install Interchange? Mamba, 0.3.0

**Comment by bieniekmateusz** [comment]
Yes, and reading the parm7 file with Sire crashes with a SEGFAULT

**Comment by mattwthompson** [comment]
This is probably https://github.com/openforcefield/openff-interchange/issues/652, which was fixed but isn't in a release yet - if you grab the most recent changes (something like `pip install git+https://github.com/openforcefield/interchange-regression-testing`) it should work

**Comment by bieniekmateusz** [comment]
Yes the dev branch works fine, thank you!

**Comment by mattwthompson** [comment]
Great, I'm making 0.3.1 now. It should be up in a few hours, or tomorrow if you're based in the UK.
